declare const styles: {
  readonly root: "root";
  readonly headerContextMenuTrigger: "headerContextMenuTrigger";
  readonly table: "table";
  readonly head: "head";
  readonly pinnedStartBoundary: "pinnedStartBoundary";
  readonly headerRow: "headerRow";
  readonly headerCell: "headerCell";
  readonly headerCellContent: "headerCellContent";
  readonly headerCellDraggable: "headerCellDraggable";
  readonly headerCellDragging: "headerCellDragging";
  readonly headerCellPinnedStart: "headerCellPinnedStart";
  readonly bodyRow: "bodyRow";
  readonly bodyRowInteractive: "bodyRowInteractive";
  readonly bodyCell: "bodyCell";
  readonly bodyRowSelected: "bodyRowSelected";
  readonly bodyCellPinnedStart: "bodyCellPinnedStart";
  readonly bodyCellMergedWithNext: "bodyCellMergedWithNext";
  readonly feedbackCell: "feedbackCell";
  readonly fetchingRow: "fetchingRow";
  readonly noData: "noData";
};
export default styles;
